// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful for verifying the MCP connection is working.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list_pages.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var BASE_URL = "https://www.shivaami.com";
var PAGES = [
  { path: "/", title: "Home", category: "Main" },
  { path: "/about-us", title: "About Us", category: "Company" },
  { path: "/leadership", title: "Leadership", category: "Company" },
  { path: "/achievements", title: "Achievements", category: "Company" },
  { path: "/certifications", title: "Certifications", category: "Company" },
  { path: "/careers", title: "Careers", category: "Company" },
  { path: "/contact", title: "Contact", category: "Company" },
  { path: "/google-workspace", title: "Google Workspace", category: "Product" },
  { path: "/google-cloud-platform", title: "Google Cloud Platform", category: "Product" },
  { path: "/gemini-enterprise", title: "Gemini Enterprise", category: "Product" },
  { path: "/google-ai-ultra", title: "Google AI Ultra", category: "Product" },
  { path: "/chrome-enterprise", title: "Chrome Enterprise", category: "Product" },
  { path: "/chromebook", title: "Chromebook", category: "Product" },
  { path: "/google-meet-hardware", title: "Google Meet Hardware", category: "Product" },
  { path: "/appsheet", title: "AppSheet", category: "Product" },
  { path: "/apps-script", title: "Apps Script", category: "Product" },
  { path: "/aws", title: "AWS", category: "Product" },
  { path: "/azure", title: "Azure", category: "Product" },
  { path: "/microsoft-365", title: "Microsoft 365", category: "Product" },
  { path: "/securesight", title: "SecureSight", category: "Product" },
  { path: "/sales-sync", title: "Gemini + Salesforce Sync", category: "Product" },
  { path: "/smarter-solutions", title: "Smarter Solutions", category: "Hub" },
  { path: "/safer-security", title: "Safer Security", category: "Hub" },
  { path: "/smoother-services", title: "Smoother Services", category: "Hub" },
  { path: "/support-packages", title: "Support Packages", category: "Support" },
  { path: "/support-services", title: "Support Services", category: "Support" },
  { path: "/case-studies", title: "Case Studies", category: "Resources" },
  { path: "/newsletter", title: "Newsletter", category: "Resources" },
  { path: "/become-partner", title: "Become a Partner", category: "Company" },
  { path: "/referral-program", title: "Referral Program", category: "Company" },
  { path: "/privacy-policy", title: "Privacy Policy", category: "Legal" },
  { path: "/terms-and-conditions", title: "Terms & Conditions", category: "Legal" }
];
var list_pages_default = defineTool2({
  name: "list_pages",
  title: "List Shivaami pages",
  description: "Returns the list of public pages on shivaami.com with titles, URLs, and categories (Company, Product, Hub, Support, Resources, Legal).",
  inputSchema: {
    category: z2.string().optional().describe("Optional filter by category (case-insensitive).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const filtered = category ? PAGES.filter((p) => p.category.toLowerCase() === category.toLowerCase()) : PAGES;
    const rows = filtered.map((p) => ({
      title: p.title,
      url: `${BASE_URL}${p.path}`,
      category: p.category
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { pages: rows }
    };
  }
});

// src/lib/mcp/tools/get_contact_info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_contact_info_default = defineTool3({
  name: "get_contact_info",
  title: "Get Shivaami contact info",
  description: "Returns Shivaami's official contact details: phone numbers, email addresses, and office locations for India and USA.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      india: {
        phone: "+91 22 6666 4225",
        email: "sales@shivaami.com",
        support: "support@shivaami.com",
        office: "Mumbai, India"
      },
      usa: {
        phone: "+1 (408) 333-4844",
        email: "sales@shivaami.com",
        support: "support@shivaami.com"
      },
      website: "https://www.shivaami.com",
      contact_page: "https://www.shivaami.com/contact"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "shivaami-mcp",
  title: "Shivaami MCP",
  version: "0.1.0",
  instructions: "Tools for Shivaami \u2014 a Google Cloud & Google Workspace partner. Use `list_pages` to discover Shivaami's public pages, `get_contact_info` for Shivaami's phone/email/offices, and `echo` to verify connectivity.",
  tools: [echo_default, list_pages_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
